#lang racket
(require (prefix-in main: cm/core/main))
(provide (all-defined-out))

(define (run str) 
  (main:run-expr str))
(define (run-silent str)
  (main:silent (main:run-expr str)))
(define (run-stat str)
  (main:run str))
(define (run-stat-silent str)
  (main:silent (main:run str)))
(define (run-file-silent str)
  (main:silent (main:run-file str)))
(define (parse str)
  (main:run-parse-expr str))
(define (tokenize str) 
  (main:run-tokenize-string str))
